### ISSUE TITLE
Great Work! Hope u can continue to update the latest work. Thanks in advance!

### ISSUE THREAD

**Issue by SuperBruceJia** [weizhou-geek/Recent-Image-Quality-Related-Papers#1]
Dear Zhou,

Thanks a lot for your wonderful work! I learned a lot of info from your repo.

Hope u can continue to update, contribute, and improve this repo. And also, update the latest work of IQA Algorithms.

Thanks in advance and have a nice day!

Best,

Shuyue

**Comment by weizhou-geek** [comment]
> Dear Zhou,
> 
> Thanks a lot for your wonderful work! I learned a lot of info from your repo.
> 
> Hope u can continue to update, contribute, and improve this repo. And also, update the latest work of IQA Algorithms.
> 
> Thanks in advance and have a nice day!
> 
> Best,
> 
> Shuyue

Dear Shuyue,

Thanks for your interest. Once I have more time, I'll update it soon.

Cheers,
Wei

**Comment by SuperBruceJia** [comment]
> > Dear Zhou,
> > Thanks a lot for your wonderful work! I learned a lot of info from your repo.
> > Hope u can continue to update, contribute, and improve this repo. And also, update the latest work of IQA Algorithms.
> > Thanks in advance and have a nice day!
> > Best,
> > Shuyue
> 
> Dear Shuyue,
> 
> Thanks for your interest. Once I have more time, I'll update it soon.
> 
> Cheers,
> Wei

Dear Wei,

Thanks a lot for your reply. I really appreciate it.

And thanks for your great summary! 

Have a wonderful day!

Best,

Shuyue
